### ISSUE TITLE
Site!

### ISSUE THREAD

**Issue by TrickJoker312** [Wade7wastaken/TrulyUnblockedGames#1]
So... what's the site?

**Comment by Wade7wastaken** [comment]
How did you even find this?

**Comment by TrickJoker312** [comment]
Well, i own a repository of unblocked game sites. I search up "unblock" and "unblocked games" every day, looking for more sites to add. Fortunately, i found this site.

**Comment by Wade7wastaken** [comment]
Well, it looks like we have the same goals. I originally made this site to play console games in school, but people requested to add links to other game sites, so thats what I did. I made a python script to scrape all the games off a few game sites and put them in a big list that can be filtered/searched. I've just been making some general improvements and plan to add a bunch more sites later.

**Comment by Wade7wastaken** [comment]
I have it running on github pages rn, but I have another "stable" version hosted elsewhere that I don't really wanna share cause I'm self hosting it

**Comment by TrickJoker312** [comment]
Oh. You have the link for the github pages?

**Comment by Wade7wastaken** [comment]
Yeah, its [here](https://wade7wastaken.github.io/TrulyUnblockedGames/). Can you not see it on github?

**Comment by Wade7wastaken** [comment]
My school blocked github pages websites, so that's why I had to host it myself.

**Comment by TrickJoker312** [comment]
No, i can't see it. Seems like a nice site! Can i add it to my repository?

**Comment by Wade7wastaken** [comment]
Ok, im gonna try to re-set up github pages. Yes, you can add it to your repo

**Comment by TrickJoker312** [comment]
Ok, thank you!
